#!/bin/bash

INPUT_FILE=$1
if ! egrep "^MOTIVO DEL COMMIT: .*, IMPLEMENTACIÓN: .*$" $INPUT_FILE &>/dev/null; then
	echo "Mensaje inválido, el formato es: "
	echo "MOTIVO DEL COMMIT: motivo, IMPLEMENTACIÓN: implementación"
	exit 1
fi

